### ISSUE TITLE
Error saat mendapatkan data

### ISSUE THREAD

**Issue by fazridep** [kresnasatya/api-harilibur#10]
Internal server error 500

**Comment by kresnasatya** [comment]
Halo @fazridep, trims infonya. Saya cek dulu.

**Comment by kresnasatya** [comment]
Halo @fazridep, saya sudah perbaiki permasalahan ini. Silakan dicek lagi ya. Saya akan tutup issue ini. Bila ada kendala silakan buka isu baru. Trims.
