### ISSUE TITLE
Holiday data for 2025 is missing

### ISSUE THREAD

**Issue by fahmipotlot** [kresnasatya/api-harilibur#11]
data holiday ditahun 2025 nya tidak ada, bisa tolong di scraping ulang untuk tahun 2025. karena tahun 2026 malah ada datanya tapi 2025 tidak ada datanya, terima kasih
https://github.com/kresnasatya/api-harilibur/tree/main/data
![image](https://github.com/kresnasatya/api-harilibur/assets/8485424/0d123474-9578-4859-a150-8f01d387deb1)

**Comment by kresnasatya** [comment]
Saya tutup issue nya ya.
