### ISSUE TITLE
Ganti nama Hari Besar Isa Al-Masih jadi Yesus Kristus

### ISSUE THREAD

**Issue by zeroxxx2** [kresnasatya/api-harilibur#13]
ref: https://bengkulu.kemenag.go.id/berita/sah-presiden-resmi-ubah-nama-hari-libur-isa-almasih-jadi-yesus-kristus-US3Sv

**Comment by kresnasatya** [comment]
Halo, maaf saya tidak bisa lakukan ini karena saya harus membuat modifikasi skrip lagi. Bayangkan kalau pejabat berganti maka kemungkinan nama hari raya akan dikembalikan di awal sehingga saya harus memodifikasi skrip lagi. Jadi, saya putuskan utk biarkan saja seperti ini dan saya serahkan kepada konsumen yang menggunakan REST API ini yang melakukan perubahan di tempat mereka. Trima kasih.
