### ISSUE TITLE
`formatted_holiday_date` tidak ada di dalam json

### ISSUE THREAD

**Issue by Allvaa** [kresnasatya/api-harilibur#4]
https://github.com/kresnasatya/api-harilibur/blob/f837ee1d670489ede5fd14b2d026b8454d9d059a/services/scraper.js#L40
https://github.com/kresnasatya/api-harilibur/blob/f837ee1d670489ede5fd14b2d026b8454d9d059a/services/scraper.js#L57
Di scraper.js terlihat properti `formatted_holiday_date` seharusnya juga ada di dalam json yang tersimpan, tetapi tidak karena type data `Date` bukan type data json yang valid.
Mungkin properti ini bisa dihilangkan sepenuhnya? Karena properti `formatted_holiday_date` tidak ada di dalam json manapun yang tersimpan dan client bisa memformat tanggal dari properti `holiday_date` sesuai keinginan mereka.

**Comment by kresnasatya** [comment]
Hi @Allvaa makasih sudah mengecek ada properti yg tidak terpakai di fungsi scraper. Apa kamu bisa dibantu utk melakukan Pull Request?
