### ISSUE TITLE
source data berubah

### ISSUE THREAD

**Issue by Ibara99** [kresnasatya/api-harilibur#6]
Saya cek (1 januari 2023) di link https://kalenderbali.org/klasik/, ada pemberitahuan kalau servicenya pindah ke https://kalenderbali.com.

sementara di scraper.js, link masih menuju ke https://kalenderbali.org/klasik/

**Comment by kresnasatya** [comment]
Halo @Ibara99, trims infonya ya. Utk sementara saya biarkan dulu dan saat ini di reposirori ini sudah menarik data sampai tahun 2024.

**Comment by kresnasatya** [comment]
Halo @Ibara99, saya sudah ganti tautan baru dari Kalender Bali. Trima kasih ya.
