### ISSUE TITLE
Error when get data

### ISSUE THREAD

**Issue by regirb** [kresnasatya/api-harilibur#9]
Hai, ada error saat mencoba get data
berikut pesannya
500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: sin1::xsdgw-1689553814871-cd8c4c80336e

**Comment by kresnasatya** [comment]
Halo @regirb, trims infonya. Saya cek dulu.

**Comment by kresnasatya** [comment]
Halo @regirb, saya sudah perbaiki ya. Silakan dicoba lagi. Saya akan tutup issue ini. Bila masih error, silakan buka issue baru. Trima kasih.

**Comment by regibiy** [comment]
sudah bisa, terima kasih @kresnasatya

**Comment by regibiy** [comment]
hai mas @kresnasatya, jika saya dapat error seperti ini
Access to fetch at 'https://api-harilibur.vercel.app/api?month=7' from origin 'https://puskesmasalianyangpnk.site' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

kenapa ya? karena sebelumnya bisa

**Comment by kresnasatya** [comment]
> hai mas @kresnasatya, jika saya dapat error seperti ini Access to fetch at 'https://api-harilibur.vercel.app/api?month=7' from origin 'https://puskesmasalianyangpnk.site' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 
> kenapa ya? karena sebelumnya bisa

Hi @regibiy, saya kelupaan pasang access-control-allow-origin di API. Skrng sudah saya pasang. Coba dicek ya.

**Comment by Setsunao** [comment]
@kresnasatya mas kayanya ini corsnya belum di allow lagi kah?
